--- # Httpd and yum playbook
- hosts: demo
  user: ansible_admin
  connection: ssh
  sudo: yes   #yes or no
  gather_facts: no # yes or no
  tasks:
    - name: install the appache server 
      action: yum name=httpd state=installed
      notify: restart httpd
    - name: install the git server
      yum: pkg=git state=installed
    - name: install git
      raw: yum list installed > /root/installed_packages.log
   
  
  handlers:
      - name: restart httpd
        action: service name=httpd state=restarted
